language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3

script:
  - phpize
  - ./configure --quiet
  - make
  - php --version
  - SHOW_ONLY_GROUPS="FAIL,XFAIL,BORK,WARN,LEAK,SKIP" REPORT_EXIT_STATUS=1 TEST_PHP_EXECUTABLE=`which php` php run-tests.php -n -d extension_dir=`pwd`/modules -d extension=dom_varimport.so -q -x --show-diff
  - phpize --clean
  - pecl package
